services:
  selenium-chrome:
    image: selenium/standalone-chrome:latest
    container_name: selenium_chrome
    ports:
      - "4444:4444"
      - "7900:7900"  
    shm_size: 2gb
    networks:
      - zstyle_network

networks:
  zstyle_network:
    name: zstyle_network
    driver: bridge
